# Generated by Django 5.2.17 on 2026-08-24 01:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Linker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('linker_code', models.CharField(blank=True, db_index=True, max_length=20, unique=True)),
                ('title', models.CharField(db_index=True, max_length=240)),
                ('description', models.TextField(blank=True)),
                ('status', models.CharField(db_index=True, default='ACTIVE', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='ResponseRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('response_mode', models.CharField(choices=[('ALL', 'All'), ('KEYWORD', 'Keyword'), ('MANUAL', 'Manual'), ('OFF', 'Off')], db_index=True, default='OFF', max_length=20)),
                ('public_reply_enabled', models.BooleanField(default=False)),
                ('private_reply_enabled', models.BooleanField(default=False)),
                ('public_reply_text', models.TextField(blank=True)),
                ('test_private_reply_text', models.TextField(default='Content Linker 자동응답 테스트입니다.')),
                ('enabled', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='SocialAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('platform', models.CharField(choices=[('INSTAGRAM', 'Instagram'), ('YOUTUBE', 'YouTube')], db_index=True, max_length=20)),
                ('account_name', models.CharField(max_length=160)),
                ('external_account_id', models.CharField(blank=True, db_index=True, max_length=255)),
                ('status', models.CharField(db_index=True, default='ACTIVE', max_length=20)),
                ('token_expires_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='ResponseKeyword',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('keyword', models.CharField(db_index=True, max_length=160)),
                ('match_type', models.CharField(default='CONTAINS', max_length=20)),
                ('enabled', models.BooleanField(default=True)),
                ('response_rule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='keywords', to='linker.responserule')),
            ],
        ),
        migrations.CreateModel(
            name='SocialContent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('platform', models.CharField(choices=[('INSTAGRAM', 'Instagram'), ('YOUTUBE', 'YouTube')], db_index=True, max_length=20)),
                ('content_type', models.CharField(choices=[('IMAGE', 'Image'), ('CAROUSEL', 'Carousel'), ('REEL', 'Reel'), ('SHORTS', 'Shorts'), ('VIDEO', 'Video')], db_index=True, max_length=20)),
                ('external_content_id', models.CharField(db_index=True, max_length=255)),
                ('title', models.CharField(blank=True, db_index=True, max_length=300)),
                ('caption', models.TextField(blank=True)),
                ('content_url', models.URLField(blank=True, max_length=1000)),
                ('thumbnail_url', models.URLField(blank=True, max_length=1000)),
                ('published_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('status', models.CharField(db_index=True, default='ACTIVE', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('linker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contents', to='linker.linker')),
                ('social_account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contents', to='linker.socialaccount')),
            ],
        ),
        migrations.CreateModel(
            name='SocialComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('external_comment_id', models.CharField(db_index=True, max_length=255, unique=True)),
                ('external_user_id', models.CharField(blank=True, db_index=True, max_length=255)),
                ('username', models.CharField(blank=True, db_index=True, max_length=255)),
                ('comment_text', models.TextField()),
                ('commented_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('received_at', models.DateTimeField(auto_now_add=True)),
                ('decision_status', models.CharField(choices=[('PENDING', 'Pending'), ('MATCHED', 'Matched'), ('NOT_MATCHED', 'Not matched'), ('MANUAL', 'Manual'), ('EXCLUDED', 'Excluded')], db_index=True, default='PENDING', max_length=20)),
                ('processing_status', models.CharField(choices=[('PENDING', 'Pending'), ('PROCESSING', 'Processing'), ('SUCCESS', 'Success'), ('FAILED', 'Failed')], db_index=True, default='PENDING', max_length=20)),
                ('social_content', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='linker.socialcontent')),
            ],
            options={
                'ordering': ['processing_status', '-received_at'],
            },
        ),
        migrations.AddField(
            model_name='responserule',
            name='social_content',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='response_rule', to='linker.socialcontent'),
        ),
        migrations.CreateModel(
            name='ResponseLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('response_type', models.CharField(choices=[('PUBLIC_REPLY', 'Public reply'), ('PRIVATE_REPLY', 'Private reply')], db_index=True, max_length=20)),
                ('response_external_id', models.CharField(blank=True, max_length=255)),
                ('status', models.CharField(db_index=True, default='PENDING', max_length=20)),
                ('error_code', models.CharField(blank=True, max_length=100)),
                ('error_message', models.TextField(blank=True)),
                ('attempted_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('social_comment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='response_logs', to='linker.socialcomment')),
            ],
            options={
                'constraints': [models.UniqueConstraint(condition=models.Q(('status', 'SUCCESS')), fields=('social_comment', 'response_type'), name='uniq_success_response_type')],
            },
        ),
        migrations.AddConstraint(
            model_name='socialcontent',
            constraint=models.UniqueConstraint(fields=('platform', 'external_content_id'), name='uniq_platform_content'),
        ),
    ]
