# Generated by Django 5.2.17 on 2026-08-24 22:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('linker', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='socialaccount',
            name='display_name',
            field=models.CharField(blank=True, max_length=160),
        ),
        migrations.AddField(
            model_name='socialaccount',
            name='memo',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='socialaccount',
            name='profile_url',
            field=models.URLField(blank=True, max_length=1000),
        ),
        migrations.AlterField(
            model_name='socialaccount',
            name='platform',
            field=models.CharField(choices=[('INSTAGRAM', 'Instagram'), ('YOUTUBE', 'YouTube'), ('TIKTOK', 'TikTok')], db_index=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='socialaccount',
            name='status',
            field=models.CharField(choices=[('ACTIVE', 'Active'), ('INACTIVE', 'Inactive'), ('SETUP_REQUIRED', 'Setup required')], db_index=True, default='ACTIVE', max_length=20),
        ),
        migrations.AlterField(
            model_name='socialcontent',
            name='platform',
            field=models.CharField(choices=[('INSTAGRAM', 'Instagram'), ('YOUTUBE', 'YouTube'), ('TIKTOK', 'TikTok')], db_index=True, max_length=20),
        ),
        migrations.AddConstraint(
            model_name='socialaccount',
            constraint=models.UniqueConstraint(condition=models.Q(('external_account_id', ''), _negated=True), fields=('platform', 'external_account_id'), name='uniq_platform_account_external_id'),
        ),
        migrations.AddConstraint(
            model_name='socialaccount',
            constraint=models.UniqueConstraint(condition=models.Q(('profile_url', ''), _negated=True), fields=('platform', 'profile_url'), name='uniq_platform_account_profile_url'),
        ),
    ]
