# Generated by Django 5.2.17 on 2026-08-24 23:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('linker', '0002_socialaccount_display_name_socialaccount_memo_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SocialCredential',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provider', models.CharField(db_index=True, default='GOOGLE_YOUTUBE', max_length=30)),
                ('access_token_encrypted', models.TextField()),
                ('refresh_token_encrypted', models.TextField(blank=True)),
                ('token_uri', models.URLField(default='https://oauth2.googleapis.com/token', max_length=500)),
                ('scopes', models.JSONField(default=list)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('channel_id', models.CharField(blank=True, max_length=255)),
                ('channel_name', models.CharField(blank=True, max_length=300)),
                ('channel_url', models.URLField(blank=True, max_length=1000)),
                ('last_verified_at', models.DateTimeField(blank=True, null=True)),
                ('oauth_status', models.CharField(choices=[('CONNECTED', 'Connected'), ('ERROR', 'Error')], db_index=True, default='CONNECTED', max_length=20)),
                ('revoked_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('social_account', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='credential', to='linker.socialaccount')),
            ],
        ),
    ]
