# Generated by Django 5.2.17 on 2026-08-25 03:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('linker', '0003_socialcredential'),
    ]

    operations = [
        migrations.AddField(
            model_name='socialcomment',
            name='metadata',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='socialcontent',
            name='metadata',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AlterField(
            model_name='socialcontent',
            name='linker',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='contents', to='linker.linker'),
        ),
    ]
