# Generated by Django 5.2.17 on 2026-08-25 06:35

import django.db.models.deletion
from django.db import migrations, models


def seed_marketplaces_and_copy_links(apps, schema_editor):
    Marketplace = apps.get_model('linker', 'Marketplace')
    Linker = apps.get_model('linker', 'Linker')
    SocialContent = apps.get_model('linker', 'SocialContent')
    SocialContentLink = apps.get_model('linker', 'SocialContentLink')
    for code, name, order in [('CP', '쿠팡', 1), ('NV', '네이버', 2), ('DM', '직판몰', 3)]:
        Marketplace.objects.get_or_create(code=code, defaults={'name': name, 'sort_order': order})
    for linker in Linker.objects.all():
        if linker.linker_code.startswith('LK-') and '_' not in linker.linker_code:
            linker.linker_group_code = linker.linker_code
            linker.destination_seq = 1
            linker.save(update_fields=['linker_group_code', 'destination_seq'])
        for content in SocialContent.objects.filter(linker=linker):
            SocialContentLink.objects.get_or_create(social_content=content, linker=linker)


def reverse_copy_links(apps, schema_editor):
    SocialContentLink = apps.get_model('linker', 'SocialContentLink')
    SocialContent = apps.get_model('linker', 'SocialContent')
    for link in SocialContentLink.objects.order_by('id'):
        content = SocialContent.objects.filter(pk=link.social_content_id, linker__isnull=True).first()
        if content:
            content.linker_id = link.linker_id
            content.save(update_fields=['linker'])


class Migration(migrations.Migration):

    dependencies = [
        ('linker', '0004_socialcomment_metadata_socialcontent_metadata_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Marketplace',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=20, unique=True)),
                ('name', models.CharField(max_length=120)),
                ('active', models.BooleanField(db_index=True, default=True)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('memo', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['sort_order', 'code'],
            },
        ),
        migrations.AddField(
            model_name='linker',
            name='destination_seq',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='linker',
            name='destination_url',
            field=models.URLField(blank=True, max_length=1000),
        ),
        migrations.AddField(
            model_name='linker',
            name='linker_group_code',
            field=models.CharField(blank=True, db_index=True, max_length=20),
        ),
        migrations.AddField(
            model_name='linker',
            name='memo',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='linker',
            name='product_no',
            field=models.CharField(blank=True, db_index=True, max_length=40),
        ),
        migrations.AddField(
            model_name='linker',
            name='thumbnail_url',
            field=models.URLField(blank=True, max_length=1000),
        ),
        migrations.AlterField(
            model_name='linker',
            name='linker_code',
            field=models.CharField(blank=True, db_index=True, max_length=40, unique=True),
        ),
        migrations.AddField(
            model_name='linker',
            name='marketplace',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='linkers', to='linker.marketplace'),
        ),
        migrations.CreateModel(
            name='SocialContentLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('display_order', models.PositiveIntegerField(default=0)),
                ('response_code', models.CharField(blank=True, max_length=40)),
                ('active', models.BooleanField(db_index=True, default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('linker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='content_links', to='linker.linker')),
                ('social_content', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_links', to='linker.socialcontent')),
            ],
            options={
                'ordering': ['display_order', 'id'],
                'constraints': [models.UniqueConstraint(fields=('social_content', 'linker'), name='uniq_social_content_linker')],
            },
        ),
        migrations.RunPython(seed_marketplaces_and_copy_links, reverse_copy_links),
    ]
