# Generated by Django 5.2.17 on 2026-08-25 13:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('linker', '0006_linker_owner_socialaccount_owner'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CreatorStore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('store_name', models.CharField(max_length=160)),
                ('slug', models.SlugField(max_length=80, unique=True)),
                ('tagline', models.CharField(blank=True, max_length=240)),
                ('profile_image', models.ImageField(blank=True, upload_to='creator/stores/profile/')),
                ('cover_image', models.ImageField(blank=True, upload_to='creator/stores/cover/')),
                ('active', models.BooleanField(db_index=True, default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('owner', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='creator_store', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
