# Generated by Django 5.2.17 on 2026-09-02 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('linker', '0016_responselog_response_rule'),
    ]

    operations = [
        migrations.AddField(
            model_name='responsekeyword',
            name='direct_url',
            field=models.URLField(blank=True, max_length=1000),
        ),
        migrations.AddField(
            model_name='responsekeyword',
            name='include_link_store',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='responsekeyword',
            name='link_mode',
            field=models.CharField(choices=[('LINK_STORE', 'Link Store'), ('DIRECT', 'Direct')], default='LINK_STORE', max_length=20),
        ),
        migrations.AddField(
            model_name='responserule',
            name='direct_url',
            field=models.URLField(blank=True, max_length=1000),
        ),
        migrations.AddField(
            model_name='responserule',
            name='include_link_store',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='responserule',
            name='link_mode',
            field=models.CharField(choices=[('LINK_STORE', 'Link Store'), ('DIRECT', 'Direct')], default='LINK_STORE', max_length=20),
        ),
    ]
