# Generated by Django 5.2.17 on 2026-09-02 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('linker', '0017_responsekeyword_direct_url_and_more'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='responselog',
            constraint=models.UniqueConstraint(fields=('social_comment', 'response_rule', 'response_type'), name='uniq_response_rule_attempt'),
        ),
    ]
