# Generated by Django 5.2.17 on 2026-09-12 03:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('linker', '0022_response_trigger_conditions'),
    ]

    operations = [
        migrations.AddField(
            model_name='linker',
            name='product_image',
            field=models.ImageField(blank=True, upload_to='creator/products/'),
        ),
    ]
