# Generated by Django 5.2.17 on 2026-09-12 03:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('linker', '0023_linker_product_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='linker',
            name='item_type',
            field=models.CharField(choices=[('PRODUCT', '상품'), ('RECIPE', '레시피'), ('SERVICE', '서비스')], db_index=True, default='PRODUCT', max_length=20),
        ),
        migrations.CreateModel(
            name='RecipeDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ingredients', models.TextField()),
                ('instructions', models.TextField()),
                ('tips', models.TextField(blank=True)),
                ('servings', models.CharField(blank=True, max_length=80)),
                ('prep_time', models.CharField(blank=True, max_length=80)),
                ('cook_time', models.CharField(blank=True, max_length=80)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('linker', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='recipe_detail', to='linker.linker')),
            ],
        ),
        migrations.CreateModel(
            name='ServiceDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_description', models.TextField(blank=True)),
                ('price_info', models.TextField(blank=True)),
                ('duration', models.CharField(blank=True, max_length=120)),
                ('location_info', models.TextField(blank=True)),
                ('contact_info', models.TextField(blank=True)),
                ('booking_url', models.URLField(blank=True, max_length=1000)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('linker', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='service_detail', to='linker.linker')),
            ],
        ),
    ]
