from django.urls import path
from . import views, creator_views

urlpatterns = [
    path('', creator_views.shoppinghub_entry, name='shoppinghub_entry'),
    path('signup/', creator_views.signup, name='signup'),
    path('shoppinghub/signup/', creator_views.signup, name='shoppinghub_signup'),

    # Creator onboarding/settings
    path('creator/onboarding/start/', creator_views.creator_onboarding_start, name='creator_onboarding_start'),
    path('creator/onboarding/store/', creator_views.creator_onboarding_store, name='creator_onboarding_store'),
    path('creator/onboarding/profile/', creator_views.creator_onboarding_profile, name='creator_onboarding_profile'),
    path('creator/onboarding/intro/', creator_views.creator_onboarding_intro, name='creator_onboarding_intro'),
    path('creator/onboarding/address/', creator_views.creator_onboarding_address, name='creator_onboarding_address'),
    path('creator/onboarding/complete/', creator_views.creator_onboarding_complete, name='creator_onboarding_complete'),
    path('creator/', creator_views.home, name='creator_home'),
    path('creator/store/switch/', creator_views.switch_store, name='creator_store_switch'),
    path('creator/store/new/', creator_views.create_store, name='creator_store_new'),
    path('creator/billing/', creator_views.creator_billing, name='creator_billing'),
    path('creator/messages/', creator_views.creator_message_templates, name='creator_message_templates'),
    path('creator/messages/new/', creator_views.creator_message_template_edit, name='creator_message_template_new'),
    path('creator/messages/<int:pk>/edit/', creator_views.creator_message_template_edit, name='creator_message_template_edit'),
    path('creator/messages/<int:pk>/copy/', creator_views.creator_message_template_copy, name='creator_message_template_copy'),
    path('creator/messages/<int:pk>/<str:action>/', creator_views.creator_message_template_action, name='creator_message_template_action'),
    path('creator/store/', creator_views.creator_store_redirect, name='creator_store'),
    path('creator/store/settings/', creator_views.hidden_user_ui_redirect, name='creator_store_settings'),
    path('creator/store/settings/', creator_views.hidden_user_ui_redirect, name='creator_store_setup'),
    path('creator/store/ready/', creator_views.hidden_user_ui_redirect, name='creator_store_ready'),
    path('creator/channels/', creator_views.social_accounts, name='creator_channels'),
    path('creator/channels/', creator_views.social_accounts, name='creator_accounts'),
    path('creator/channels/<int:pk>/instagram/sync/', creator_views.instagram_sync, name='creator_instagram_sync'),
    path('creator/channels/youtube/connect/', creator_views.youtube_auto_connect, name='creator_youtube_connect'),
    path('creator/channels/youtube/connect/', creator_views.youtube_auto_connect, name='youtube_auto_connect'),
    path('creator/channels/<int:pk>/youtube/verify/', views.youtube_verify, name='creator_youtube_verify'),
    path('creator/channels/<int:pk>/youtube/disconnect/', creator_views.youtube_disconnect, name='creator_youtube_disconnect'),
    path('creator/channels/instagram/connect/', creator_views.instagram_auto_connect, name='creator_instagram_connect'),
    path('creator/channels/instagram/connect/', creator_views.instagram_auto_connect, name='instagram_auto_connect'),
    path('creator/channels/<int:pk>/instagram/connect/', creator_views.instagram_connect, name='creator_instagram_account_connect'),
    path('creator/channels/<int:pk>/instagram/connect/', creator_views.instagram_connect, name='instagram_connect'),
    path('creator/channels/<int:pk>/instagram/reauthorize/', creator_views.instagram_reauthorize, name='creator_instagram_reauthorize'),
    path('creator/channels/<int:pk>/instagram/reauthorize/', creator_views.instagram_reauthorize, name='instagram_reauthorize'),
    path('creator/channels/<int:pk>/instagram/verify/', creator_views.instagram_verify, name='creator_instagram_verify'),
    path('creator/channels/<int:pk>/instagram/verify/', creator_views.instagram_verify, name='instagram_verify'),
    path('creator/channels/<int:pk>/instagram/primary/', creator_views.creator_set_primary, name='creator_instagram_set_primary'),
    path('creator/channels/<int:pk>/instagram/disconnect/', creator_views.instagram_disconnect, name='creator_instagram_disconnect'),
    path('creator/channels/<int:pk>/instagram/disconnect/', creator_views.instagram_disconnect, name='instagram_disconnect'),

    # OAuth callbacks: retain exact external paths so existing Meta/Google console settings can be reused.
    path('oauth/instagram/callback/', creator_views.instagram_callback, name='instagram_callback'),
    path('oauth/instagram/auto/callback/', creator_views.instagram_auto_callback, name='instagram_auto_callback'),
    path('oauth/youtube/auto/callback/', creator_views.youtube_auto_callback, name='youtube_auto_callback'),
    path('oauth/youtube/callback/', views.youtube_callback, name='youtube_callback'),

    # ShoppingHub work area
    path('shoppinghub/', creator_views.home, name='shoppinghub_home'),
    path('shoppinghub/stats/', creator_views.shoppinghub_stats, name='shoppinghub_stats'),
    path('shoppinghub/products/', creator_views.creator_products, name='shoppinghub_products'),
    path('shoppinghub/products/', creator_views.creator_products, name='creator_products'),
    path('shoppinghub/products/new/', creator_views.shoppinghub_product_new, name='shoppinghub_product_new'),
    path('shoppinghub/products/<int:pk>/edit/', creator_views.shoppinghub_product_edit, name='shoppinghub_product_edit'),
    path('shoppinghub/products/actions/', creator_views.creator_products, name='shoppinghub_product_actions'),
    path('shoppinghub/blocks/new/', creator_views.shoppinghub_block_new, name='shoppinghub_block_new'),
    path('shoppinghub/blocks/<int:pk>/edit/', creator_views.shoppinghub_block_edit, name='shoppinghub_block_edit'),
    path('shoppinghub/display/', creator_views.creator_products, name='shoppinghub_display'),
    path('shoppinghub/store/', creator_views.creator_store_redirect, name='shoppinghub_store'),
    path('shoppinghub/contents/', creator_views.creator_contents, name='shoppinghub_contents'),
    path('shoppinghub/contents/', creator_views.creator_contents, name='creator_contents'),
    path('shoppinghub/contents/<int:pk>/', creator_views.creator_content_detail, name='shoppinghub_content_detail'),
    path('shoppinghub/contents/<int:pk>/', creator_views.creator_content_detail, name='creator_content_detail'),
    path('shoppinghub/contents/<int:pk>/products/add/', creator_views.creator_link_add, name='shoppinghub_content_link_add'),
    path('shoppinghub/contents/<int:pk>/products/add/', creator_views.creator_link_add, name='creator_link_add'),
    path('shoppinghub/comments/', creator_views.creator_reactions, name='shoppinghub_comments'),
    path('shoppinghub/comments/', creator_views.creator_reactions, name='creator_reactions'),
    path('shoppinghub/auto-dm/', creator_views.auto_dm_wizard, name='shoppinghub_auto_dm'),
    path('shoppinghub/auto-dm/<int:pk>/toggle/', creator_views.auto_dm_toggle, name='shoppinghub_auto_dm_toggle'),
    path('shoppinghub/auto-dm/<int:pk>/delete/', creator_views.auto_dm_delete, name='shoppinghub_auto_dm_delete'),
    path('shoppinghub/accounts/<int:pk>/youtube/content/', views.youtube_content_import, name='shoppinghub_youtube_content_import'),

    # Public store
    path('s/<slug:slug>/', creator_views.public_store, name='public_store'),
    path('s/<slug:slug>/out/<int:pk>/', creator_views.public_store_outbound, name='public_store_outbound'),

    # Staff workspace only
    path('workspace/', views.dashboard, name='workspace_home'),
    path('workspace/accounts/', views.accounts, name='workspace_accounts'),
    path('workspace/accounts/new/', views.account_onboarding, name='workspace_account_onboarding'),
    path('workspace/accounts/<int:pk>/toggle/', views.toggle_account, name='workspace_account_toggle'),
    path('workspace/accounts/<int:pk>/youtube/connect/', views.youtube_connect, name='workspace_youtube_connect'),
    path('workspace/accounts/<int:pk>/youtube/reauthorize/', views.youtube_reauthorize, name='workspace_youtube_reauthorize'),
    path('workspace/accounts/<int:pk>/youtube/verify/', views.youtube_verify, name='workspace_youtube_verify'),
    path('workspace/accounts/<int:pk>/youtube/disconnect/', views.youtube_disconnect, name='workspace_youtube_disconnect'),
    path('workspace/accounts/<int:pk>/youtube/content/', views.youtube_content_import, name='workspace_youtube_content_import'),
    path('workspace/accounts/<int:pk>/youtube/content/register/', views.youtube_content_register, name='workspace_youtube_content_register'),
    path('workspace/linkers/', views.linkers, name='workspace_linkers'),
    path('workspace/linkers/search/', views.linker_search, name='workspace_linker_search'),
    path('workspace/marketplaces/', views.marketplaces, name='workspace_marketplaces'),
    path('workspace/contents/', views.contents, name='workspace_contents'),
    path('workspace/contents/<int:pk>/youtube/comments/', views.youtube_comment_sync, name='workspace_youtube_comment_sync'),
    path('workspace/contents/<int:pk>/links/add/', views.content_link_add, name='workspace_content_link_add'),
    path('workspace/content-links/<int:pk>/remove/', views.content_link_remove, name='workspace_content_link_remove'),
    path('workspace/rules/', views.rules, name='workspace_rules'),
    path('workspace/comments/', views.comments, name='workspace_comments'),
    path('workspace/comments/<int:pk>/retry/', views.retry_comment, name='workspace_retry_comment'),
    path('workspace/comments/<int:pk>/exclude/', views.exclude_comment, name='workspace_exclude_comment'),
    path('workspace/logs/', views.logs, name='workspace_logs'),

    path('privacy/', views.privacy_policy, name='privacy_policy'),
    path('data-deletion/', views.data_deletion, name='data_deletion'),
    path('webhooks/instagram/', views.instagram_webhook, name='instagram_webhook'),
]
